---
- name: my first module with ansible
  hosts: all 
  tasks:

  - name: my first task
    debug: 
      msg: "Hello Yash"
  - name: my first task
    debug:
      msg: "Hello Salman"
  - name: my first task
    debug:
      msg: "Hello Tiger"
  - name: my first task
    debug:
      msg: "Hello Suraj"
...

